// photos array lives in photos-data.js (generated by scripts/build-photos.mjs)

function formatDate(dateStr) {
  if (!dateStr) return null;
  const [y, m, d] = dateStr.split('-').map(Number);
  return new Date(y, m - 1, d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function formatTime(timeStr) {
  if (!timeStr) return null;
  const [h, m] = timeStr.split(':').map(Number);
  return new Date(2000, 0, 1, h, m).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
}

function formatCamera(p) {
  const bits = [];
  if (p.camera) bits.push(p.camera);
  if (p.focalLength) bits.push(`${p.focalLength}mm`);
  if (p.aperture) bits.push(`f/${p.aperture}`);
  return bits.join(' · ');
}

function cardMetaHtml(p) {
  const dateLine = p.date ? formatDate(p.date) + (p.time ? ` · ${formatTime(p.time)}` : '') : 'Date unknown';
  const camLine = formatCamera(p);
  const camHtml = camLine ? `<span class="cam">${camLine}</span>` : '';
  const locLine = p.location ? `<span class="loc">${p.location}</span>` : '';
  return `${dateLine}${camHtml}${locLine}`;
}

const grid = document.getElementById('photo-grid');
const emptyState = document.getElementById('photo-empty');

if (!photos || photos.length === 0) {
  emptyState.style.display = 'block';
} else {
  grid.innerHTML = photos
    .map(
      (p, i) => `
    <button type="button" class="photo-card" data-index="${i}" aria-label="View ${p.file}">
      <img src="${p.thumb || p.src}" alt="" loading="lazy" decoding="async" />
      <span class="photo-card-meta">${cardMetaHtml(p)}</span>
    </button>`
    )
    .join('');
}

// ── Masonry (CSS Grid + measured row spans) ────────────────────────
// Keeps items in left-to-right, top-to-bottom reading order (unlike
// CSS multi-column, which fills one column at a time).
function layoutMasonry() {
  const styles = getComputedStyle(grid);
  const rowHeight = parseFloat(styles.gridAutoRows) || 4;
  const rowGap = parseFloat(styles.rowGap) || 0;
  grid.querySelectorAll('.photo-card').forEach((card) => {
    const span = Math.ceil((card.getBoundingClientRect().height + rowGap) / (rowHeight + rowGap));
    card.style.gridRowEnd = `span ${span}`;
  });
}

grid.querySelectorAll('.photo-card img').forEach((img) => {
  if (img.complete) layoutMasonry();
  else img.addEventListener('load', layoutMasonry);
});
layoutMasonry();

let resizeTimer;
window.addEventListener('resize', () => {
  clearTimeout(resizeTimer);
  resizeTimer = setTimeout(layoutMasonry, 150);
});

// ── Lightbox ──────────────────────────────────────────────────────
const overlay = document.getElementById('lightbox-overlay');
const lbImg = document.getElementById('lightbox-img');
const lbProgressWrap = document.getElementById('lightbox-progress');
const lbProgressBar = document.getElementById('lightbox-progress-bar');
const lbDate = document.getElementById('lightbox-date');
const lbCamera = document.getElementById('lightbox-camera');
const lbLocation = document.getElementById('lightbox-location');

let current = 0;
let currentObjectUrl = null;
let currentAbort = null;

// Streams the full-res original so the progress bar reflects actual bytes
// downloaded (these originals can be tens of MB), instead of a generic spinner.
async function loadFullRes(p, idx) {
  if (currentAbort) currentAbort.abort();
  const controller = new AbortController();
  currentAbort = controller;

  lbProgressBar.style.width = '0%';
  lbProgressWrap.classList.add('active');

  try {
    const res = await fetch(p.src, { signal: controller.signal });
    const total = Number(res.headers.get('content-length')) || 0;
    const reader = res.body.getReader();
    const chunks = [];
    let received = 0;

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      chunks.push(value);
      received += value.length;
      if (total) lbProgressBar.style.width = `${Math.min(100, (received / total) * 100)}%`;
    }

    if (current !== idx) return; // navigated away before this finished

    const url = URL.createObjectURL(new Blob(chunks));
    if (currentObjectUrl) URL.revokeObjectURL(currentObjectUrl);
    currentObjectUrl = url;
    lbImg.src = url;
  } catch (err) {
    if (err.name === 'AbortError') return;
    if (current === idx) lbImg.src = p.src; // streaming unsupported/failed — plain load fallback
  } finally {
    if (current === idx) {
      lbProgressBar.style.width = '100%';
      setTimeout(() => {
        if (current === idx) lbProgressWrap.classList.remove('active');
      }, 200);
    }
  }
}

function renderLightbox() {
  const idx = current;
  const p = photos[idx];

  // Show the already-cached thumbnail instantly, then swap to the full-res
  // original once it's loaded — avoids flashing the previously-viewed photo
  // while the new one downloads (plain <img> keeps showing its old src).
  lbImg.src = p.thumb || p.src;
  lbImg.alt = p.file;
  loadFullRes(p, idx);

  lbDate.textContent = p.date ? `${formatDate(p.date)}${p.time ? ` · ${formatTime(p.time)}` : ''}` : 'Date unknown';
  const camLine = formatCamera(p);
  lbCamera.textContent = camLine;
  lbCamera.style.display = camLine ? 'block' : 'none';
  lbLocation.textContent = p.location || '';
  lbLocation.style.display = p.location ? 'block' : 'none';
}

function openLightbox(index) {
  current = index;
  renderLightbox();
  overlay.classList.add('open');
  document.body.style.overflow = 'hidden';
}

function closeLightbox() {
  overlay.classList.remove('open');
  document.body.style.overflow = '';
}

function step(delta) {
  current = (current + delta + photos.length) % photos.length;
  renderLightbox();
}

grid.querySelectorAll('.photo-card').forEach((card) => {
  card.addEventListener('click', () => openLightbox(Number(card.dataset.index)));
});

document.getElementById('lightbox-close').addEventListener('click', closeLightbox);
document.getElementById('lightbox-prev').addEventListener('click', () => step(-1));
document.getElementById('lightbox-next').addEventListener('click', () => step(1));
overlay.addEventListener('click', (e) => {
  if (e.target === overlay) closeLightbox();
});
document.addEventListener('keydown', (e) => {
  if (!overlay.classList.contains('open')) return;
  if (e.key === 'Escape') closeLightbox();
  if (e.key === 'ArrowLeft') step(-1);
  if (e.key === 'ArrowRight') step(1);
});
