const projects = [
  {
    id: '915mhz',
    title: 'Encrypted 915 MHz Transceiver',
    context: 'Personal Project',
    date: '2026',
    image: null,
    gradient: 'linear-gradient(135deg, #80a1d4 0%, #1a2a4a 100%)',
    summary: 'Custom 915 MHz RF transceiver with hardware-level AES encryption for secure wireless data links.',
    description: 'Designing a custom 915 MHz ISM-band transceiver with hardware AES-128 encryption for secure, low-latency wireless communication. Targets applications in autonomous systems and telemetry where link security is critical.',
    bullets: [
      'RF front-end design targeting 915 MHz ISM band with dedicated LNA, PA, and impedance-matched antenna interface',
      'Hardware AES-128 encryption block ensures data security at the physical layer with minimal latency overhead',
      'STM32-based baseband processing with custom packet framing, error correction, and link-layer protocol',
    ],
    tags: ['RF Design', '915 MHz', 'AES Encryption', 'STM32', 'PCB Design', 'Wireless'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M5 12.55a11 11 0 0 1 14.08 0"/><path d="M1.42 9a16 16 0 0 1 21.16 0"/><path d="M8.53 16.11a6 6 0 0 1 6.95 0"/><circle cx="12" cy="20" r="1" fill="currentColor"/></svg>`,
  },
  {
    id: 'mako-longfin',
    title: 'Mako Longfin',
    context: 'Personal Project',
    date: '2026',
    image: null,
    model: './images/makolongfin2.glb',
    gradient: 'linear-gradient(135deg, #4a7fa5 0%, #1a3a52 100%)',
    summary: 'Details coming soon.',
    description: 'Details coming soon.',
    bullets: [
      'Fill in project details here',
    ],
    tags: ['PCB Design'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M4.22 4.22l2.12 2.12M17.66 17.66l2.12 2.12M2 12h3M19 12h3M4.22 19.78l2.12-2.12M17.66 6.34l2.12-2.12"/></svg>`,
  },
  {
    id: 'mako',
    title: 'Mako Shortfin — 1.5 kW FOC Motor Controller',
    context: 'Personal Project',
    date: '2025 – 2026',
    image: null,
    model: './images/makoshortfin.glb',
    gradient: 'linear-gradient(135deg, #e9724c 0%, #6b2d18 100%)',
    summary: 'Full bring-up of a 1.5 kW FOC inverter — 30 kHz switching, 25 A peak AC, closed-loop current + velocity control.',
    description: 'Designed and brought up a 1.5 kW Field-Oriented Control inverter for BLDC motors: 30 kHz switching at 25 A peak AC current from a 60 V DC bus using Infineon OptiMOS MOSFETs and UCC27211A half-bridge gate drivers.',
    bullets: [
      '4-layer mixed-signal PCB with 2 oz inner-layer copper, cascaded buck-converter bias rails, and isolated analog/digital returns for low-noise current sensing',
      'STM32G474 firmware implementing synchronized 3-phase inline current sampling and A1333 SPI magnetic encoder feedback in a 30 kHz FOC loop',
      'Achieved closed-loop current and velocity control with real-time commutation and field weakening',
    ],
    tags: ['STM32G474', 'FOC', 'Power Electronics', 'Altium Designer', 'C/C++', '4-Layer PCB', 'Gate Drivers'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M4.22 4.22l2.12 2.12M17.66 17.66l2.12 2.12M2 12h3M19 12h3M4.22 19.78l2.12-2.12M17.66 6.34l2.12-2.12"/></svg>`,
  },
  {
    id: 'bms',
    title: 'GR26 Battery Management System',
    context: 'UCSB Gaucho Racing',
    date: 'Sept 2025',
    image: null,
    model: './images/BMS.glb',
    gradient: 'linear-gradient(135deg, #e9724c 0%, #80a1d4 100%)',
    summary: 'Segment-level BMS PCB using NXP MC33771C AFE — 39% board area reduction vs GR25.',
    description: 'Designed schematic and 4-layer PCB for GR26 segment-level BMS modules using NXP MC33771C AFE in a 2p140s configuration — achieved 39% board area reduction vs GR25, improving pack packaging density and thermal margin.',
    bullets: [
      'STM32G474 thermistor acquisition for 14 temperature points per segment with 10-sample moving-average filter achieving <0.5°C noise floor',
      'TPL (Transformer Physical Layer) daisy-chain across 10 modules with capacitive isolation for cell monitoring and passive balancing',
    ],
    tags: ['STM32G474', 'NXP MC33771C', 'BMS', 'TPL', 'Altium Designer', '4-Layer PCB'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 7V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2"/><line x1="12" y1="12" x2="12" y2="16"/><line x1="10" y1="14" x2="14" y2="14"/></svg>`,
  },
  {
    id: 'harness',
    title: 'GR26 Wire Harness Architecture',
    context: 'UCSB Gaucho Racing',
    date: 'Dec 2025',
    image: null,
    model: './images/wireharness.glb',
    modelOrbit: { theta: 295, phi: 65 },
    gradient: 'linear-gradient(135deg, #e9724c 0%, #333333 100%)',
    summary: 'Full-vehicle electrical schematic across 8 subsystems with wire-level documentation for fabrication.',
    description: 'Developed full-vehicle electrical schematic in RapidHarness mapping power, CAN, and analog signal paths across 8 subsystems, then routed the harness in SolidWorks Routing maintaining FSAE clearance through monocoque.',
    bullets: [
      'Exported wire-level documentation for fabrication with connector, splice, and shield assignments',
      'Specified shielded twisted-pair CAN, DR25 heat-shrink covering, and Deutsch motorsport connectors for EMI-resilient interconnect under vibration',
      'Optimized routing for pit-lane serviceability while meeting all FSAE structural clearance requirements',
    ],
    tags: ['RapidHarness', 'SolidWorks', 'CAN Bus', 'Deutsch Connectors', 'FSAE', 'EMI'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4 9h16M4 15h16M10 3 8 21M16 3l-2 18"/></svg>`,
  },
  {
    id: 'sensor-network',
    title: 'Distributed Sensor Network',
    context: 'UCSB Gaucho Racing',
    date: 'Dec 2024',
    image: './images/sensnetworkthumb.png',
    gradient: 'linear-gradient(135deg, #333333 0%, #0f110c 100%)',
    summary: 'CAN-based data acquisition network with custom PCB nodes and IP67-rated enclosures for GR25.',
    description: 'Architected CAN-based sensor network for GR25 data acquisition with custom PCB nodes featuring integrated sensor ICs and IP67-rated enclosures for harsh racing environments.',
    bullets: [
      'Custom PCB nodes with integrated sensor ICs and on-board CAN transceiver for distributed data acquisition',
      'Modular IP67 enclosures in SolidWorks with laser-cut acrylic, silicone gaskets, and threaded inserts — field replacement under 2 minutes',
    ],
    tags: ['CAN Bus', 'PCB Design', 'SolidWorks', 'IP67', 'Data Acquisition'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M5 12.55a11 11 0 0 1 14.08 0"/><path d="M1.42 9a16 16 0 0 1 21.16 0"/><path d="M8.53 16.11a6 6 0 0 1 6.95 0"/><circle cx="12" cy="20" r="1" fill="currentColor"/></svg>`,
  },
];
