const projects = [
  {
    id: '915mhz',
    title: 'Encrypted 915 MHz Transceiver',
    context: 'Personal Project',
    date: '2026',
    image: null,
    gradient: 'linear-gradient(135deg, #80a1d4 0%, #1a2a4a 100%)',
    summary: 'Custom 915 MHz RF transceiver with hardware-level AES encryption for secure wireless data links.',
    description: 'Designing a custom 915 MHz ISM-band transceiver with hardware AES-128 encryption for secure, low-latency wireless communication. Targets applications in autonomous systems and telemetry where link security is critical.',
    bullets: [
      'RF front-end design targeting 915 MHz ISM band with dedicated LNA, PA, and impedance-matched antenna interface',
      'Hardware AES-128 encryption block ensures data security at the physical layer with minimal latency overhead',
      'STM32-based baseband processing with custom packet framing, error correction, and link-layer protocol',
    ],
    tags: ['RF Design', '915 MHz', 'AES Encryption', 'STM32', 'PCB Design', 'Wireless'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M5 12.55a11 11 0 0 1 14.08 0"/><path d="M1.42 9a16 16 0 0 1 21.16 0"/><path d="M8.53 16.11a6 6 0 0 1 6.95 0"/><circle cx="12" cy="20" r="1" fill="currentColor"/></svg>`,
  },
  {
    id: 'mako-longfin',
    title: 'Mako Longfin — 4.5 kW 3-Motor FOC Inverter',
    context: 'Personal Project',
    date: '2026',
    image: null,
    model: './images/3dmodels/makolongfin2-v1.glb',
    thumb: './images/img%20thumbs/longfin.png',
    gradient: 'linear-gradient(135deg, #4a7fa5 0%, #1a3a52 100%)',
    summary: 'Next-revision 4.5 kW inverter extending Mako Shortfin to simultaneous FOC control of three BLDC motors from a single STM32 MCU.',
    description: 'Designed as the direct successor to Mako Shortfin, Mako Longfin scales the architecture to 4.5 kW across three independent motor channels — each with its own discrete power stage — all driven by a single STM32 running three parallel FOC loops.',
    bullets: [
      'Triple discrete power stage with per-phase current sensing on each channel; single STM32 runs three synchronized 30 kHz FOC loops with independent d-q current controllers',
      '4-layer mixed-signal PCB with expanded power delivery network supporting 3× the phase current paths of Mako Shortfin while maintaining isolated analog and digital returns',
      'Cascaded bus-to-12V-to-5V-to-3.3V power conversion retained from Shortfin; 5V rail exposed externally for three independent encoder sensor interfaces',
    ],
    tags: ['STM32', 'FOC', 'Power Electronics', 'Altium Designer', '4-Layer PCB', 'Gate Drivers', 'Multi-Motor'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M4.22 4.22l2.12 2.12M17.66 17.66l2.12 2.12M2 12h3M19 12h3M4.22 19.78l2.12-2.12M17.66 6.34l2.12-2.12"/></svg>`,
  },
  {
    id: 'mako',
    title: 'Mako Shortfin — 1.5 kW FOC Motor Controller',
    context: 'Personal Project',
    date: '2025 – 2026',
    image: null,
    model: './images/3dmodels/makoshortfin-v1.glb',
    thumb: './images/img%20thumbs/shortfin.png',
    gradient: 'linear-gradient(135deg, #e9724c 0%, #6b2d18 100%)',
    summary: 'Full bring-up of a 1.5 kW FOC inverter — 30 kHz switching, 25 A peak AC, closed-loop current + velocity control.',
    description: 'Designed and brought up a 1.5 kW Field-Oriented Control inverter for BLDC motors: 30 kHz switching at 25 A peak AC current from a 60 V DC bus using Infineon OptiMOS MOSFETs and UCC27211A half-bridge gate drivers.',
    bullets: [
      '4-layer mixed-signal PCB with 2 oz inner-layer copper, cascaded buck-converter bias rails, and isolated analog/digital returns for low-noise current sensing',
      'STM32G474 firmware implementing synchronized 3-phase inline current sampling and A1333 SPI magnetic encoder feedback in a 30 kHz FOC loop',
      'Achieved closed-loop current and velocity control with real-time commutation and field weakening',
    ],
    tags: ['STM32G474', 'FOC', 'Power Electronics', 'Altium Designer', 'C/C++', '4-Layer PCB', 'Gate Drivers'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M4.22 4.22l2.12 2.12M17.66 17.66l2.12 2.12M2 12h3M19 12h3M4.22 19.78l2.12-2.12M17.66 6.34l2.12-2.12"/></svg>`,
  },
  {
    id: 'bms',
    title: 'GR26 Battery Management System',
    context: 'UCSB Gaucho Racing',
    date: 'Sept 2025',
    image: null,
    model: './images/3dmodels/BMS-v1.glb',
    thumb: './images/img%20thumbs/bms.png',
    gradient: 'linear-gradient(135deg, #e9724c 0%, #80a1d4 100%)',
    summary: 'Segment-level BMS PCB using NXP MC33771C AFE for GR26\'s 144S2P 588V pack — 39% board area reduction vs GR25.',
    description: 'Designed schematic and 4-layer PCB for GR26 segment-level BMS modules using NXP MC33771C AFE. The tractive system runs a 2p140s (588V) configuration requiring 10 modules daisy-chained via capacitive-isolation TPL — achieved 39% board area reduction vs GR25 with deliberate clearance and isolation gap choices for high-voltage reliability.',
    bullets: [
      'STM32G474RE thermistor acquisition for 14 temperature points per segment with 10-sample moving-average filter achieving <0.5°C noise floor',
      'TPL daisy-chain across all 10 modules with capacitive isolation; layout clearances and isolation gaps sized for 588V tractive system reliability per FSAE EV rules',
    ],
    tags: ['STM32G474', 'NXP MC33771C', 'BMS', 'TPL', 'Altium Designer', '4-Layer PCB'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 7V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2"/><line x1="12" y1="12" x2="12" y2="16"/><line x1="10" y1="14" x2="14" y2="14"/></svg>`,
  },
  {
    id: 'harness',
    title: 'GR26 Wire Harness Architecture',
    context: 'UCSB Gaucho Racing',
    date: 'Dec 2025',
    image: null,
    model: './images/3dmodels/wireharness-v1.glb',
    thumb: './images/img%20thumbs/wireharness.png',
    modelOrbit: { theta: 295, phi: 65, radius: '60%' },
    gradient: 'linear-gradient(135deg, #e9724c 0%, #333333 100%)',
    summary: 'Full-vehicle electrical schematic across 8 subsystems with wire-level documentation for fabrication.',
    description: 'Developed full-vehicle electrical schematic in RapidHarness mapping power, CAN, and analog signal paths across 8 subsystems, then routed the harness in SolidWorks Routing maintaining FSAE clearance through monocoque.',
    bullets: [
      'Exported wire-level documentation for fabrication with connector, splice, and shield assignments',
      'Specified shielded twisted-pair CAN, DR25 heat-shrink covering, and Deutsch motorsport connectors for EMI-resilient interconnect under vibration',
      'Optimized routing for pit-lane serviceability while meeting all FSAE structural clearance requirements',
    ],
    tags: ['RapidHarness', 'SolidWorks', 'CAN Bus', 'Deutsch Connectors', 'FSAE', 'EMI'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4 9h16M4 15h16M10 3 8 21M16 3l-2 18"/></svg>`,
  },
  {
    id: 'sensor-network',
    title: 'Distributed Sensor Network',
    context: 'UCSB Gaucho Racing',
    date: 'Dec 2024',
    image: './images/sensnetworkthumb.png',
    gradient: 'linear-gradient(135deg, #333333 0%, #0f110c 100%)',
    summary: '$2k URCA-funded CANFD sensor network for GR25 — 17 custom nodes across chassis, suspension, and thermal subsystems with a dedicated Orin Nano TCM.',
    description: 'Received a $2,000 UCSB URCA grant with three teammates to design, manufacture, and deploy a full CANFD sensor network for GR25. Built 17 custom nodes (5 chassis, 4 suspension, 8 thermal) each with a custom SAM PCB, sensor daughter cards, and 3D-printed gasketed enclosures. A dedicated Telecommunications Module running an Nvidia Orin Nano aggregated all data over CANFD, stored it in a SingleStore database, and relayed it via LTE. Tested on-car at Willow Springs International Raceway.',
    bullets: [
      'STM32G474RE Sensor Array Module (SAM) with dual CANFD transceivers and 12V/5V/3.3V rails; daughter PCBs per node type carrying BMI323 IMU, VL53LXX ToF, InertialSense IG-2-IMX-5, load cell conditioners, potentiometer ports, MS4525DO air speed, and MLX90640/614 thermal arrays',
      'Telecommunications Module (TCM) built on Nvidia Orin Nano with CAN interface, LTE router, and internal battery — acts as on-board black box logging all sensor streams to SingleStore',
      '3D-printed two-part DTM 4-pin enclosures with cut rubber gasketing; chassis nodes mount via single bolt and zip tie directly to chassis tubes for minimal packaging impact',
    ],
    tags: ['CAN Bus', 'STM32G474RE', 'PCB Design', 'SolidWorks', 'Data Acquisition', 'Nvidia Orin Nano', 'URCA Grant'],
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M5 12.55a11 11 0 0 1 14.08 0"/><path d="M1.42 9a16 16 0 0 1 21.16 0"/><path d="M8.53 16.11a6 6 0 0 1 6.95 0"/><circle cx="12" cy="20" r="1" fill="currentColor"/></svg>`,
  },
];
